---

- name: Create a 2048-bit SSH key for users in ~/.ssh/id_rsa
  become: True
  ansible.builtin.user:
    name: "{{ item.username }}"
    comment: "{{ item.gecos }}"
    shell: /bin/bash
    groups: docker
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
  with_items:
    - "{{ users }}"

- name: Set up authorized keys for users
  become: True
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{% for key in item.pkeys %}{{ key ~ '\n' }}{% endfor %}"
  with_items:
    - "{{ users }}"

- name: Allow the users to run any commands sudo
  become: True
  community.general.sudoers:
    name: "{{ item.username }}"
    state: present
    user: "{{ item.username }}"
    commands: ALL
  with_items:
    - "{{ users }}"
  when: item.sudo == True
