
global:
  checknewversion: false
  sendanonymoususage: false

api:
  # insecure: true
  dashboard: true
  debug: true

log:
  level: DEBUG
  format: common
accessLog: {}


certificatesResolvers:
  letsEncrypt:
    acme:
      email: ""
      storage: "/etc/traefik/acme/acme.json"
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # tlsChallenge: {}
      httpChallenge:
        entryPoint: http

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"

providers:
  providersThrottleDuration: 10s

  http:
    endpoint: "http://{{ proxy_oam_ip }}:8888/api/config"
    pollInterval: "10s"
