global:
  scrape_interval: 10s

scrape_configs:
 - job_name: prometheus
  metrics_path: /metrics
  static_configs:
    - targets:
      - locahost:9090
 - job_name: traefik
  metrics_path: /metrics
  static_configs:
    - targets:
      - http://traefik.dev.
